<!-- This code was generated by Builder.io -->
<div class="profile-section">
  <div class="profile-image" role="img" aria-label="User profile" />
  <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/2a01ab1d-ac75-4e1d-baf6-788132c74da1?placeholderIfAbsent=true&apiKey=7d82fdb3593d4b2699db1ab59e93f211" alt="Profile options" class="profile-options" />
</div>

<style>
.profile-section {
  align-self: stretch;
  display: flex;
  gap: 10px;
}

.profile-image {
  background-color: #d9d9d9;
  border-radius: 50%;
  width: 26px;
  height: 26px;
  margin: auto 0;
}

.profile-options {
  aspect-ratio: 2.8;
  object-fit: contain;
  object-position: center;
  width: 182px;
  max-width: 100%;
}
</style>