<!-- This code was generated by Builder.io -->
<div class="search-container">
  <div class="search-icon-wrapper">
    <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/db40a64519d6d88556f137a58c90af895b83e82f891023a2798f7524a9a74e2c?placeholderIfAbsent=true&apiKey=7d82fdb3593d4b2699db1ab59e93f211" alt="Search icon" class="search-icon" />
  </div>
  <div class="search-input-wrapper">
    <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/e397bcdae1326ef679dcb1bf2684cc4ffe5c19e5e4e3e55347dfcd24af82ac38?placeholderIfAbsent=true&apiKey=7d82fdb3593d4b2699db1ab59e93f211" alt="Input icon" class="input-icon" />
    <input type="text" placeholder="Enter some text..." class="search-input" aria-label="Search input" />
  </div>
</div>

<style>
.search-container {
  display: flex;
  gap: 6px;
}

.search-icon-wrapper {
  border-radius: 3px;
  background-color: #edf3f7;
  display: flex;
  padding: 6px 7px;
}

.search-icon {
  aspect-ratio: 1;
  object-fit: contain;
  object-position: center;
  width: 22px;
}

.search-input-wrapper {
  border-radius: 3px;
  background-color: #edf3f7;
  display: flex;
  align-items: center;
  gap: 7px;
  padding: 2px 0;
}

.input-icon {
  aspect-ratio: 1.03;
  object-fit: contain;
  object-position: center;
  width: 31px;
}

.search-input {
  border: none;
  background: transparent;
  font: 400 20px Inter, sans-serif;
  color: #000;
  margin-left: 20px;
}

.search-input::placeholder {
  color: #000;
}

@media (max-width: 991px) {
  .search-icon-wrapper {
    padding-right: 20px;
  }
}
</style>