<!-- This code was generated by Builder.io -->
<section class="filter-section">
  <div class="filter-option">
    <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/bb58a2937086542628bfcbb2bc91287558845307f4b4f4eda501b652441bb351?placeholderIfAbsent=true&apiKey=7d82fdb3593d4b2699db1ab59e93f211" alt="" class="filter-icon" />
    <span class="filter-text">Filters</span>
  </div>
  <div class="filter-option">
    <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/b96d1ad6a42334ef34e97e422ea939eb3c62e53fad0d028aa60f51b7a221e970?placeholderIfAbsent=true&apiKey=7d82fdb3593d4b2699db1ab59e93f211" alt="" class="filter-icon" />
    <span class="filter-text">Anti-Filters</span>
  </div>
</section>

<style>
.filter-section {
  background-color: #fff;
  display: flex;
  flex-direction: column;
  color: #171818;
  font: 400 20px Inter, sans-serif;
  border: 1px solid #e8e8e8;
  padding-bottom: 322px;
}

.filter-option {
  position: relative;
  max-width: 205px;
  padding: 17px 70px 29px;
  margin-bottom: 20px;
}

.filter-icon {
  position: absolute;
  inset: 0;
  height: 100%;
  width: 100%;
  object-fit: cover;
  object-position: center;
}

.filter-text {
  position: relative;
  z-index: 1;
}

@media (max-width: 991px) {
  .filter-section {
    margin-top: 13px;
    padding-bottom: 100px;
  }

  .filter-option {
    padding: 17px 20px;
  }
}
</style>