<!-- This code was generated by Builder.io -->
<script>
import SearchBar from './SearchBar.svelte';
import ProfileSection from './ProfileSection.svelte';
import FilterSection from './FilterSection.svelte';
import BoardSection from './BoardSection.svelte';
</script>

<main class="job-search">
  <header class="top-bar">
    <nav class="navigation">
      <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/475939f9761762372b9a8e10e8150290ec108f91d6eaa91f3dc5e48d8ab01830?placeholderIfAbsent=true&apiKey=7d82fdb3593d4b2699db1ab59e93f211" alt="Navigation icon" class="nav-icon" />
      <SearchBar />
      <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/a40fa3b7bd608ef8863f4a965db35ef9ff3087a10b53550fc284702fb2705631?placeholderIfAbsent=true&apiKey=7d82fdb3593d4b2699db1ab59e93f211" alt="Additional navigation icon" class="additional-nav-icon" />
    </nav>
    <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/8aabb5f872f4b10b905e3ae9c641c37dd251c877d1bdca5ebd5f4126de1f8b66?placeholderIfAbsent=true&apiKey=7d82fdb3593d4b2699db1ab59e93f211" alt="Company logo" class="company-logo" />
    <ProfileSection />
  </header>
  
  <div class="content-wrapper">
    <aside class="sidebar">
      <FilterSection />
    </aside>
    <BoardSection />
  </div>
</main>

<style>
.job-search {
  background-color: #f4f2ee;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  margin-bottom: 200px;
}

.top-bar {
  background-color: #fff;
  display: flex;
  align-items: center;
  gap: 15px;
  flex-wrap: wrap;
  padding: 1px 80px;
  border: 1px solid #e8e8e8;
}

.navigation {
  align-self: stretch;
  display: flex;
  gap: 6px;
  flex-wrap: wrap;
  margin: auto 0;
}

.nav-icon, .additional-nav-icon {
  aspect-ratio: 1;
  object-fit: contain;
  object-position: center;
  width: 35px;
  margin: auto 0;
}

.company-logo {
  aspect-ratio: 7.41;
  object-fit: contain;
  object-position: center;
  width: 259px;
  align-self: stretch;
  max-width: 100%;
  margin: auto 0;
}

.content-wrapper {
  align-self: center;
  width: 100%;
  max-width: 1074px;
  display: flex;
  gap: 20px;
}

.sidebar {
  width: 19%;
}

@media (max-width: 991px) {
  .top-bar {
    padding: 0 20px;
  }

  .navigation {
    max-width: 100%;
  }

  .content-wrapper {
    flex-direction: column;
    align-items: stretch;
    gap: 0;
    max-width: 100%;
  }

  .sidebar {
    width: 100%;
  }
}
</style>