<!-- This code was generated by Builder.io -->
<section class="board-section">
  <header class="board-header"></header>
  <div class="board-content"></div>
</section>

<style>
.board-section {
  background-color: #fff;
  box-shadow: 0 4px 4px rgba(0, 0, 0, 0.25);
  display: flex;
  flex-grow: 1;
  padding-right: 80px;
  flex-direction: column;
  align-items: flex-start;
  width: 81%;
  border: 1px solid #e8e8e8;
}

.board-header {
  background-color: #0b66c2;
  width: 385px;
  max-width: 100%;
  height: 59px;
}

.board-content {
  background-color: #fff;
  width: 385px;
  max-width: 100%;
  height: 705px;
  border: 1px solid #e8e8e8;
}

@media (max-width: 991px) {
  .board-section {
    width: 100%;
    max-width: 100%;
    margin-top: 13px;
    padding-right: 0;
  }
}
</style>